# -*- coding: utf-8 -*-
"""
define common used parameters for simplecfs
"""

# successful operation return
RET_SUCCESS = True

# failed operation return
RET_FAILURE = False

# ==== code define ====
CODE_RS = 'RS'
CODE_CRS = 'CRS'
CODE_Z = 'ZCODE'

# ==== DS defined parameters ====

# ds type
DS_LOCAL = 'local'
DS_MEMORY = 'memory'

# ds state
DS_CONNECTED = 'OK'
DS_BROKEN = 'FAILED'

# chunk state
CHUNK_OK = 1000
CHUNK_MISSING = 1001
CHUNK_BREAK = 1002   # when DS is break
# CHUNK_DAMAGED = 1003

# data send and recv frame size
DATA_FRAME_SIZE = 8192  # 8K

# ==== operations ====

# ---- operations between client and ds
OP_ADD_CHUNK = 'ADD_CHUNK'
OP_ADD_CHUNK_REPLY = 'ADD_CHUNK_REPLY'

OP_DELETE_CHUNK = 'DELETE_CHUNK'
OP_DELETE_CHUNK_REPLY = 'DELETE_CHUNK_REPLY'

OP_GET_CHUNK = 'GET_CHUNK'
OP_GET_CHUNK_REPLY = 'GET_CHUNK_REPLY'

# ---- operations between ds and mds
OP_ADD_DS = 'ADD_DS'
OP_ADD_DS_REPLY = 'ADD_DS_REPLY'

OP_CHECK_CHUNK = 'CHECK_CHUNK'
OP_CHECK_CHUNK_REPLY = 'CHECK_CHUNK_REPLY'

OP_REPORT_DS = 'REPORT_DS'
OP_REPORT_DS_REPLY = 'REPORT_DS_REPLY'

# ---- operation between client and mds ----
OP_MAKE_DIR = 'MAKE_DIR'
OP_MAKE_DIR_REPLY = 'MAKE_DIR_REPLY'

OP_REMOVE_DIR = 'REMOVE_DIR'
OP_REMOVE_DIR_REPLY = 'REMOVE_DIR_REPLY'

OP_LIST_DIR = 'LIST_DIR'
OP_LIST_DIR_REPLY = 'LIST_DIR_REPLY'

OP_STATUS_DIR = 'STATUS_DIR'
OP_STATUS_DIR_REPLY = 'STATUS_DIR_REPLY'

OP_VALID_DIR = 'VALID_DIR'
OP_VALID_DIR_REPLY = 'VALID_DIR_REPLY'

OP_ADD_FILE = 'ADD_FILE'
OP_ADD_FILE_REPLY = 'ADD_FILE_REPLY'

OP_ADD_FILE_COMMIT = 'ADD_FILE_COMMIT'
OP_ADD_FILE_COMMIT_REPLY = 'ADD_FILE_COMMIT_REPLY'

OP_STAT_FILE = 'STAT_FILE'
OP_STAT_FILE_REPLY = 'STAT_FILE_REPLY'

OP_DELETE_FILE = 'DELETE_FILE'
OP_DELETE_FILE_REPLY = 'DELETE_FILE_REPLY'

OP_GET_FILE = 'GET_FILE'
OP_GET_FILE_REPLY = 'GET_FILE_REPLY'

OP_GET_OBJ = 'GET_OBJ'
OP_GET_OBJ_REPLY = 'GET_OBJ_REPLY'

OP_GET_CHK = 'GET_CHK'
OP_GET_CHK_REPLY = 'GET_CHK_REPLY'

OP_REPAIR_CHK = 'REPAIR_CHK'
OP_REPAIR_CHK_REPLY = 'REPAIR_CHK_REPLY'

OP_REPAIR_CHK_COMMIT = 'REPAIR_CHK_COMMIT'
OP_REPAIR_CHK_COMMIT_REPLY = 'REPAIR_CHK_COMMIT_REPLY'
